### ISSUE TITLE
figure out how NOSA table column names cross-walk to those in the Excel sheets

### ISSUE THREAD

**Issue by eeholmes** [nwfsc-math-bio/rCAX#1]
[cax_colnames.csv](https://github.com/nwfsc-math-bio/rCAX/files/10143820/cax_colnames.csv)

**Comment by katiebarnas** [comment]
I did a quick comparison. All the stuff we really want (NMFS_POPID, TRTMETHOD, POP_FIT) doesn't come through on the back end data grab. See column F for what I got in a download the wasn't in the data grab. 
Both ways have a mismatch. Eli's csv had 6 headers that the regular download doesn't have.

**Comment by mari-williams** [comment]
[cax_colnames.xlsx](https://github.com/nwfsc-math-bio/rCAX/files/10156929/cax_colnames.xlsx)
I sent this over to Greg @streamnet and haven't heard back yet on the discrepancies. Note the first comparison column was from the 2020 SR download and column c was downloaded 11/23. Differences between 2020 and 2022 are updates to the DES.

**Comment by eeholmes** [comment]
Download_nomatch

**These are ok. They are in the Populations table**
ESAPOPNAME <- This is ok. It is in the Populations table
NMFS_POPID <- This is ok. It is in the Populations table
POPULATIONNAME <- This is ok. It is in the Populations table
CONTACTAGY <- seems to be a shortened version of CONTACTAGENCY

**No idea where these come from. I couldn't find them in any table and no info on the REST API documentation**
DATASETVERSION
HLI_LASTUPDATED
LASTMODIFIEDON
LASTUPDATED
LOCATIONNAME
SNLOADDATE
TRTMETHOD

**Here are the headers from NOSA API that are not in the download**
num <- seems to be some kind of sorting reference
publish
dataentry <- completely missing
escapementlat
escapementlong
escapementtiming

**Comment by eeholmes** [comment]
Found the Download table!  It is "XPortCA_NOSA_01"

It is listed with their tables but had no description so I hadn't tried it yet: https://nwfsc-math-bio.github.io/rCAX/articles/CAX_Tables.html

**Comment by eeholmes** [comment]
Ok, I am going to close this since all the missing table headers are in "XPortCA_NOSA_01". So this is done.

**Comment by mari-williams** [comment]
Yup. I am going to keep following up with SN staff about it - the 'we' from
that side of my work need to make sure we're serving what we should be for
pulls. It appears we (NOAA us!) are the first real pull users, all the
issues we're seeing are structured around folks pushing data via the API.
Yay for feedback!!!
