### ISSUE TITLE
Add DOI for Zenodo and update the citation info

### ISSUE THREAD

**Issue by eeholmes** [nwfsc-math-bio/rCAX#14]
- [x] add doi - add to Zenodo before making the 1.0.0 release
- [x] add Mari and Katie to the citation
- [x] RCMD check
- [x] goodpractice::gp()

https://f1000research.com/about
https://peerj.com/preprints/3304v1/

**Comment by eeholmes** [comment]
@mari-williams Before we share this with a bigger audience, it'd be good to have someone we know try it out and catch typos and anything weird. I was thinking Thomas and Neala since they might want to use it so might be motivated to try it out. Anyone else you can think of?

**Comment by mari-williams** [comment]
I missed this completely. I'm sorry!
