### ISSUE TITLE
Review the "terms" message on library loading. Sufficient?

### ISSUE THREAD

**Issue by mari-williams** [nwfsc-math-bio/rCAX#27]
Can we 'insert' this somewhere in the beginning and have an 'accept' box to click before proceeding? I really don't know what I'm asking for in terms of code, just looking to set up a small stumbling block where folks see this before they download data - as they would via the front end.

**Comment by eeholmes** [comment]
@mari-williams I added a start up message when you first type `library(rCAX)`

Access and use of data in the CAX databases requires acceptance of the terms of use: type rcax_termsofuse() at the command line to see the terms.

**Comment by eeholmes** [comment]
Alternatively, I could actually have a Y/N accept terms of use message and require the user to say Y. Might get irritating...

**Comment by mari-williams** [comment]
Let's keep that in the back of our minds but not implement it while we are futzing around.
