### ISSUE TITLE
https://nwfsc-math-bio.github.io/rCAX/reference/rcax_hli_xport.html This one is verbose but just check if there are any glaring problems

### ISSUE THREAD

**Issue by mari-williams** [nwfsc-math-bio/rCAX#28]
I want to edit some verbage on this like I did on the readme, but it wants me to branch to edit and I'm thinking I should come back to this.

**Comment by eeholmes** [comment]
You can make a branch. Nothing bad will happen. When done click button for a "pull request" and then it'll ping me to merge it.

**Comment by mari-williams** [comment]
Ok, feedback on how that came through? because i made a branch and then it asked if i wanted to save changes to that or to the branch and generate a pull request.

**Comment by eeholmes** [comment]
@mari-williams Worked great! I merged in the changes.
