### ISSUE TITLE
Delete rcax_hli.r, not needed

### ISSUE THREAD

**Issue by mari-williams** [nwfsc-math-bio/rCAX#29]
Honestly my gut says let's toss this version and only set up pulls from the XPORT table because it has the metadata we want (NMFS_popid) and I like metadata (a primary benefit of CAX).

**Comment by eeholmes** [comment]
Ok, I'll delete rcax_hli. We can always get the base tables using `rcax_tables_query()` if needed.

**Comment by eeholmes** [comment]
Completed
