### ISSUE TITLE
get column descriptions for the tables

### ISSUE THREAD

**Issue by eeholmes** [nwfsc-math-bio/rCAX#6]
In the 3 tab for the Excel files that are downloaded, there is a file with definitions of all the columns. I could not find that table in the API tables but I am guessing it might be somewhere in the database. I searched everywhere and couldn't find it. While we could just create it from the Excel file, it'd be best if I can download it from the API so it stays synced.

@mari-williams Can you ask the CAX folks where it might be?

![Image](https://user-images.githubusercontent.com/2545978/206069473-2f953252-0159-496f-a7ea-dae105b966ba.png)

**Comment by eeholmes** [comment]
If we can't download, then I'll do a temporary fix by getting the definitions from the Excel files and save into data.

**Comment by eeholmes** [comment]
@mari-williams I created the definition table using the definitions from the downloaded Excel files. So I think we are ok unless the definitions change, and then our definitions will be out of sync.

**Comment by mari-williams** [comment]
@eeholmes I will ask, this is great feedback!

**Comment by eeholmes** [comment]
@mari-williams There are 2 colnames that I cannot figure out: "trtmethod" and "hli_id" . 

trtmethod is "Yes", "No", or "" in the tables. Does not appear in the definitions tabs on any of the HLI Excel files.

hli_id does not seem to be associated with a hli. like NOSA does not have one number. Does not match any other ids (like popid or nmfs_popid). Numbers like 5  19  21  59  83 172 201 227 237 357

Do you know what these are?

**Comment by mari-williams** [comment]
We have moved away from trtmethod. It was originally intended to mark the collection and analysis methods that were developed and used by the TRT in status assessment. Data entry folks took to using it as 'NOAA will look at my data if I say yes' and as we got farther from the end of the TRT and data gaps filled and new methodology became available (and valid alt datastreams came online) it became confusing and was dissolved as we move towards a 'dataset' column along with the 'best value' column per contributor.
I'm looking and finding nothing about hli_id. asking.

**Comment by eeholmes** [comment]
Ok, I'll remove trtmethod from the output then

**Comment by mari-williams** [comment]
yes, make the nightmare be gone!!!

**Comment by mari-williams** [comment]
hli_id is probably the programmers internal tracking of pages or such. i'm going to clarify with him, but right now the understanding is that it's not data or anything representing data

**Comment by eeholmes** [comment]
Thanks, Mike and Greg!

On Wed, Dec 7, 2022 at 1:08 PM Mike Banach <[mike_banach@psmfc.org](mailto:mike_banach@psmfc.org)> wrote:
Hi Mari.

Eli should now be able to directly access field definitions via the StreamNet API.

The GUID for the table is BD0C3244-B688-4C3E-BE18-21AF0E9E5FCB.
Table name is zwq_FieldDefinitions.  The table has a few fields that are not
useful but she should be able to easily find and use what she's after.

Mike

**Comment by eeholmes** [comment]
Closing this as I have a working solution. I'll code up getting the data from the zwq_FieldDefinitions table for a later update to the package.
